---
apiVersion: v1
kind: Pod
metadata:
  name: ns1-pod
  namespace: ns1
  annotations:
    ovn.kubernetes.io/logical_switch: ns1-subnet1
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: pod-cust-vpc1
      image: docker.io/nicolaka/netshoot:latest
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - "sleep infinity"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

