# 目前认为 vip 以及 pod 切换 ip 但是 fip 不变
# 会导致出现目前解决不了的网络问题
# vip fip 不通
# pod ip fip ping 首包，丢 10 个包以上
# 可能跟 vip 没有 lsp 有关系，没有在流表层精确维护

---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived01-0
spec:
  externalSubnet: external
  #v4Ip: 192.168.7.4
  type: nat

---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived01-1
spec:
  externalSubnet: external
  #v4Ip: 192.168.7.5
  type: nat