---
kind: Vip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived-vip
spec:
  subnet: vpc1-subnet1
  type: ""

---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived-eip
spec:
  externalSubnet: external
  type: nat

---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived-fip
spec:
  ovnEip: keepalived-eip
  ipType: vip         # 默认情况下 fip 是面向 pod ip 的，这里需要标注指定对接到 vip 资源
  ipName: keepalived-vip

---
kind: KeepAlived
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  name: vpc1-subnet1-keepalived-01
  namespace: ns1
spec:
  image: icoy/kube-combo-keepalived:v0.0.1
  subnet: vpc1-subnet1
  vipV4: 10.1.0.2 
  vipV6: 

# vip is the ip address of vip
# todo:// support duastack 