---
kind: KeepAlived
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  name: vpc1-subnet1-keepalived-01
  namespace: ns1
spec:
  image: icoy/kube-combo-keepalived:v0.0.1
  subnet: vpc1-subnet1
  vipV4: 10.1.0.49
  # 每次测试都要重新指定实际的 vip
  vipV6: 

# vip is the ip address of vip
# todo:// support duastack 

---
kind: VpnGw
apiVersion: vpn-gw.kubecombo.com/v1
metadata:
  name: keepalived01
  namespace: ns1
spec:
  cpu: "1"
  memory: "1024M"
  qosBandwidth: "20"
  replicas: 2 # vrrp 要求至少 2 个节点
  selector:
  tolerations:
  affinity:
  enableSslVpn: true
  sslVpnSecret: ovpnsrv
  dhSecret: ssl-vpn-dh-pem
  sslVpnImage: icoy/kube-combo-openvpn:v0.0.1
  sslVpnCipher: AES-256-GCM
  sslVpnAuth: SHA1
  sslVpnProto: udp
  sslVpnSubnetCidr: 10.240.0.0/16
  enableIpsecVpn: false
  ipsecSecret: ovpn-0-ipsec-vpn
  ipsecVpnImage: icoy/kube-combo-strongswan:v0.0.1
  keepalived: "vpc1-subnet1-keepalived-01"

# 该模版仅用于验证 keepalived crd 被 vpn gw 引用，可以提供一个高可用的 vip
#

---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived01-0
spec:
  ovnEip: keepalived01-0
  ipName: keepalived01-0.ns1

---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: keepalived01-1
spec:
  ovnEip: keepalived01-1
  ipName: keepalived01-1.ns1

