---
kind: OvnEip
apiVersion: kubeovn.io/v1
metadata:
  name: nginx
spec:
  externalSubnet: external
  v4Ip: 192.168.0.110
  type: fip

---
kind: OvnFip
apiVersion: kubeovn.io/v1
metadata:
  name: nginx
spec:
  ovnEip: nginx
  ipName: vpc1-nginx.ns1


---
apiVersion: v1
kind: Pod
metadata:
  name: vpc1-nginx
  namespace: ns1
  annotations:
    ovn.kubernetes.io/logical_switch: vpc1-subnet1
spec:
  containers:
    - name: nginx
      image: nginx:latest
    - name: netshoot
      image: docker.io/nicolaka/netshoot:latest
      imagePullPolicy: Never
      command:
        - sh
        - -c
        - "sleep infinity"
      securityContext:
        capabilities:
          add:
            - NET_ADMIN

